In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([11,12,13,14,15,16,17,18,19,20])

### shape

In [3]:
a.shape

(10,)

In [4]:
b.shape

(10,)

### Dimensions

In [5]:
a.ndim

1

In [6]:
b.ndim

1

### Type of the Array

In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

numpy.ndarray

### Data type of the array contents 

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

### Length of the array

In [11]:
len(a)

10

In [12]:
len(b)

10

### Change the shape of the array

In [13]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
b.reshape(5,2)

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### Concatination of two arrays

In [15]:
ab=np.concatenate((a,b))

In [16]:
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### For finding position of the array content

In [17]:
bc=np.where(a==4)

In [18]:
bc

(array([3], dtype=int64),)

In [19]:
cd=np.where(b==15)

In [20]:
cd

(array([4], dtype=int64),)

### Array split

In [21]:
sp=np.array_split(a,3)

In [22]:
sp

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [23]:
sp1=np.array_split(b,4)

In [24]:
sp1

[array([11, 12, 13]), array([14, 15, 16]), array([17, 18]), array([19, 20])]

### Array Iteration

In [26]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
for x in c:
    x2=x+10
    print(x2)
    for y in x:
        x1=x2+100
        print(x1)

[11 12 13]
[111 112 113]
[111 112 113]
[111 112 113]
[14 15 16]
[114 115 116]
[114 115 116]
[114 115 116]
[17 18 19]
[117 118 119]
[117 118 119]
[117 118 119]
[21 22 23]
[121 122 123]
[121 122 123]
[121 122 123]
